In [139]:
import gym
import numpy as np
import torch.nn as nn
import torch.optim as optim
import os
import torch
import math

In [25]:
class ActorNetwork(nn.Module):
    def __init__(self, n_actions, input_dims, alpha,
                fc1_dims=256, fc2_dims=256, chkpt_dir='./tmp/ppo'):
        super(ActorNetwork, self).__init__()
        
        self.checkpoint_file=os.path.join(chkpt_dir, 'actor_torch_ppo')
        self.actor = nn.Sequential(
            nn.Linear(*input_dims, fc1_dims),
            nn.ReLU(),
            nn.Linear(fc1_dims, fc2_dims),
            nn.ReLU(),
            nn.Linear(fc2_dims, n_actions),
            nn.Softmax(dim=-1)
        )
        self.optimizer = optim.Adam(self.parameters(), lr=alpha)
        #self.device = 
        
    
    def forward(self, state):
        pass
    
    def save_checkpoint(self):
        pass
    
    def load_checkpoint(self):
        pass

In [26]:
class CriticNetwork(nn.Module):
    def __init__(self):
        pass
    
    def forward(self, state):
        pass
    
    def save_checkpoint(self):
        pass
    
    def load_checkpoint(self):
        pass

In [27]:
class Agent:
    def __init__(self, n_actions, input_dims, gamma=0.99, 
                alpha=0.0003, gae_lambda=0.95, policy_clip=0.2, 
                batch_size=64, n_epochs=10):
        self.gamma = gamma
        self.policy_clip = policy_clip
        self.n_epochs = n_epochs
        self.gae_lambda = gae_lambda
        
        self.actor = ActorNetwork(n_actions, input_dims, alpha)
    
    def remember(self):
        pass
    
    def save_models(self):
        pass
    
    def load_models(self):
        pass
    
    def choose_action(self, observation):
        pass
    
    def learn(self):
        pass
    
        

In [29]:
env = gym.make('CartPole-v0')
N = 20
batch_size = 5
n_epochs = 4
alpha = 0.0003

agent = Agent(n_actions=env.action_space.n, batch_size=batch_size,
             alpha=alpha, n_epochs=n_epochs, input_dims=env.observation_space.shape)

n_games = 300

best_score = env.reward_range[0]
score_history = []

learn_iters = 0
avg_score = 0
n_steps = 0

observation = env.reset()
done = False
score = 0
while not done:
    action, prob, val = agent.choose_action(observation)

/u/samar/.conda/envs/rl/lib/python3.9/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


TypeError: cannot unpack non-iterable NoneType object

In [52]:
t1 = torch.tensor([[1,4,4], [4,5,6]])
t2 = torch.randn(10,10)

In [59]:
t2.shape

torch.Size([10, 10])

In [60]:
t2.size()

torch.Size([10, 10])

In [47]:
t1.unbind(dim=0)

(tensor([1, 4, 4]), tensor([4, 5, 6]))

In [51]:
torch.unbind(t1, dim=1)

(tensor([1, 4]), tensor([4, 5]), tensor([4, 6]))

In [50]:
torch.unique(t1, dim=1)

tensor([[1, 4, 4],
        [4, 5, 6]])

In [61]:
t1

tensor([[1, 4, 4],
        [4, 5, 6]])

In [66]:
t3=torch.randn(2,3,4)
t3

tensor([[[-0.2956,  1.3429,  0.1534,  0.6527],
         [-0.4973, -1.7180, -1.3210,  0.6957],
         [ 0.3175, -1.3622,  1.5633, -0.5228]],

        [[-0.0097,  0.2967,  2.0934,  0.2879],
         [ 2.7146,  0.9189, -1.3161,  0.0951],
         [-1.0411, -0.2537,  0.7328, -1.3536]]])

In [72]:
t4 = t3.movedim(2,0)
t4

tensor([[[-0.2956, -0.4973,  0.3175],
         [-0.0097,  2.7146, -1.0411]],

        [[ 1.3429, -1.7180, -1.3622],
         [ 0.2967,  0.9189, -0.2537]],

        [[ 0.1534, -1.3210,  1.5633],
         [ 2.0934, -1.3161,  0.7328]],

        [[ 0.6527,  0.6957, -0.5228],
         [ 0.2879,  0.0951, -1.3536]]])

In [73]:
t4.shape

torch.Size([4, 2, 3])

In [74]:
t3.shape

torch.Size([2, 3, 4])

In [75]:
t5 = torch.randn(2,1,3)
t5

tensor([[[ 0.5461,  0.5930, -0.9034]],

        [[ 0.2467, -0.2575,  0.6066]]])

In [76]:
t5.squeeze()

tensor([[ 0.5461,  0.5930, -0.9034],
        [ 0.2467, -0.2575,  0.6066]])

In [77]:
torch.squeeze(t5)

tensor([[ 0.5461,  0.5930, -0.9034],
        [ 0.2467, -0.2575,  0.6066]])

In [80]:
t5.shape, t5.squeeze().shape

(torch.Size([2, 1, 3]), torch.Size([2, 3]))

In [102]:
dist = torch.distributions.gumbel.Gumbel(torch.tensor([1.0]), torch.tensor([2.0]))
dist

Gumbel(loc: tensor([1.]), scale: tensor([2.]))

In [103]:
dist.sample()

tensor([12.0253])

In [104]:
dist.entropy()

tensor([2.2704])

In [105]:
dist.log_prob(torch.tensor([1.2]))

tensor([-1.6980])

In [108]:
dist.mean, dist.stddev

(tensor([2.1544]), tensor([2.5651]))

In [110]:
dist.support

Real()

In [112]:
dist.variance

tensor([6.5797])

In [147]:
loc = torch.tensor([0.0])
scale = torch.tensor([1.0])
norm = torch.distributions.normal.Normal(loc=loc, scale=scale)
norm

Normal(loc: tensor([0.]), scale: tensor([1.]))

In [148]:
norm.mean, norm.stddev, norm.variance

(tensor([0.]), tensor([1.]), tensor([1.]))

In [149]:
norm.sample()

tensor([-1.1773])

In [150]:
norm.entropy()

tensor([1.4189])

In [151]:
norm.arg_constraints

{'loc': Real(), 'scale': GreaterThan(lower_bound=0.0)}

In [157]:
value = torch.tensor([0.0])
norm.log_prob(value)

tensor([-0.9189])

In [156]:
x = 1.0
-x*x/2.0 -0.5 * math.log(2*math.pi)

-1.4189385332046727

In [159]:
norm.cdf(scale)

tensor([0.8413])

In [162]:
probs = torch.tensor([0.2, 0.7, 0.1])
cat = torch.distributions.categorical.Categorical(probs)
cat

Categorical(probs: torch.Size([3]))

In [174]:
value = cat.sample()
value

tensor(2)

In [179]:
np.arange(0,20,64)

array([0])

In [194]:
batch_start = np.arange(0, 10, 5)
indices = np.arange(10)
np.random.shuffle(indices)
batches = [indices[i:i+5] for i in batch_start]
indices, batch_start, batches

(array([2, 9, 4, 5, 0, 7, 6, 1, 3, 8]),
 array([0, 5]),
 [array([2, 9, 4, 5, 0]), array([7, 6, 1, 3, 8])])