In [1]:
from torch_geometric.datasets import QM9

In [23]:
help(QM9)

Help on class QM9 in module torch_geometric.datasets.qm9:

class QM9(torch_geometric.data.in_memory_dataset.InMemoryDataset)
 |  QM9(root, transform=None, pre_transform=None, pre_filter=None)
 |  
 |  The QM9 dataset from the `"MoleculeNet: A Benchmark for Molecular
 |  Machine Learning" <https://arxiv.org/abs/1703.00564>`_ paper, consisting of
 |  about 130,000 molecules with 19 regression targets.
 |  Each molecule includes complete spatial information for the single low
 |  energy conformation of the atoms in the molecule.
 |  In addition, we provide the atom features from the `"Neural Message
 |  Passing for Quantum Chemistry" <https://arxiv.org/abs/1704.01212>`_ paper.
 |  
 |  +--------+----------------------------------+-----------------------------------------------------------------------------------+---------------------------------------------+
 |  | Target | Property                         | Description                                                                       

In [24]:
dataset = QM9(root='data/QM9')

In [25]:
len(dataset)

130831

In [26]:
data = dataset[0]

In [27]:
dataset.num_node_features

11

In [28]:
dataset.num_edge_features

4

In [29]:
data.num_nodes

5

In [30]:
data.num_edges

8

In [31]:
data

Data(edge_attr=[8, 4], edge_index=[2, 8], idx=[1], name="gdb_1", pos=[5, 3], x=[5, 11], y=[1, 19], z=[5])

In [32]:
data.x

tensor([[0., 1., 0., 0., 0., 6., 0., 0., 0., 0., 4.],
        [1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.]])

In [33]:
data.edge_index.t()

tensor([[0, 1],
        [0, 2],
        [0, 3],
        [0, 4],
        [1, 0],
        [2, 0],
        [3, 0],
        [4, 0]])

In [15]:
data.is_undirected()

tensor(True)

In [16]:
data.num_nodes

5

In [19]:
data.y.t()

tensor([[    0.0000],
        [   13.2100],
        [  -10.5499],
        [    3.1865],
        [   13.7363],
        [   35.3641],
        [    1.2177],
        [-1101.4878],
        [-1101.4098],
        [-1101.3840],
        [-1102.0229],
        [    6.4690],
        [  -17.1722],
        [  -17.2868],
        [  -17.3897],
        [  -16.1519],
        [  157.7118],
        [  157.7100],
        [  157.7070]])

In [20]:
data.pos

tensor([[-1.2700e-02,  1.0858e+00,  8.0000e-03],
        [ 2.2000e-03, -6.0000e-03,  2.0000e-03],
        [ 1.0117e+00,  1.4638e+00,  3.0000e-04],
        [-5.4080e-01,  1.4475e+00, -8.7660e-01],
        [-5.2380e-01,  1.4379e+00,  9.0640e-01]])

In [22]:
type(data.edge_attr)

torch.Tensor